alias: "Rotex Defrost "
description: ""
trigger:
  - platform: state
    entity_id:
      - sensor.rotex_betriebart
    to: Abtauen
  - platform: state
    entity_id:
      - sensor.rotex_betriebart
    to: Heizen
  - platform: state
    entity_id:
      - sensor.rotex_betriebart
    from: Warmwasserbereitung
    to: Standby
condition: []
action:
  - if:
      - condition: state
        entity_id: sensor.rotex_betriebart
        state: Abtauen
    then:
      - device_id: 2a5626837f08ce84a7f4b3ec31079af7
        domain: select
        entity_id: a1f5a43a56340e3cd1924d9d435848b3
        type: select_option
        option: Sommer
      - service: notify.christoph
        metadata: {}
        data:
          message: es wird abgetaut!!
    else: []
  - if:
      - condition: state
        entity_id: sensor.rotex_betriebart
        state: Heizen
    then:
      - device_id: 2a5626837f08ce84a7f4b3ec31079af7
        domain: select
        entity_id: a1f5a43a56340e3cd1924d9d435848b3
        type: select_option
        option: Heizen
      - service: 
        metadata: {}
        data:
          message: es wird geheizt!!
    else: []
  - if:
      - condition: state
        entity_id: sensor.rotex_betriebart
        state: Standby
    then:
      - device_id: 2a5626837f08ce84a7f4b3ec31079af7
        domain: select
        entity_id: a1f5a43a56340e3cd1924d9d435848b3
        type: select_option
        option: Heizen
      - service: 
        metadata: {}
        data:
          message: es wird geheizt!!
    else: []
mode: single
